routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

/** @var Router $router */

use Illuminate\Routing\Router;

$router->get('/', function () {
    return view('welcome');
});

// Authentication Routes...
$router->get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('throttle:5,1');
$router->post('login', 'Auth\LoginController@login')->middleware('throttle:5,1');
$router->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//$router->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//$router->post('register', 'Auth\RegisterController@register');

//$router->get('/fresh-users', function() {
//    App\User::all()->each(function(\App\User $user) {
//        $user->delete();
//    });
//});

// Password Reset Routes...
$router->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$router->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$router->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$router->post('password/reset', 'Auth\ResetPasswordController@reset');



$router->group(['prefix' => 'admin', 'middleware' => 'auth'], function(Router $router) {

	$router->resources([
		'categories'	=> 'CategoriesController',
		'products'		=> 'ProductsController',
		'orders'		=> 'OrdersController',
	]);
});

$router->get('/home', 'HomeController@index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;

class Category extends Model
{
	/**
	 * Mass assignment attributes.
	 * 	
	 * @var array
	 */
    protected $fillable = ['name', 'status'];

    protected $casts = [
    	'id'	=> 'int',
    	'status'	=> 'int',
    ];

    public static function boot()
    {
    	parent::boot();

    	static::deleted(function($category) {

            /*
             * Delete all relalated products
             */
    		$category->products->each(function(Product $product) {
    			$product->delete();
    		});

            /*
             * Delete related images.
             * We not sure that it exists, so get images relation as collection
             * And map every image.
             *
             * If image will have required rule it can be changed to
             *
             * $product->image->delete();
             */
    		$category->image()->get()->each(function(Image $image) {
                $image->delete();
            });
    	});
    }

    /**
     * Category image relation.
     * 
     * @return MorphOne
     */
    public function image()
    {
    	return $this->morphOne(Image::class, 'imagable');
    }

    /**
     * Category products relation.
     * 
     * @return HasMany 
     */
    public function products()
    {
    	return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Image;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index', [
            'categories'    => Category::latest()->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreCategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = Category::create($request->all());

        // store category image
        if ($request->file('image')) {
            $fileName = $category->id . '.' . $request->file('image')->extension();
            $request->file('image')->storeAs('images/categories', $fileName);

            $category->image()->create(['path'  => $fileName]);
        }
        
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return $category;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateCategoryRequest  $request
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->fill($request->all())->save();

        if ($image = $request->file('image')) {

            /*
             * Delete previous images
             */
            $category->image()->get()->each(function(Image $image) {
                $image->delete();
            });

            $fileName = $category->id . '.' .$image->extension();
            $image->storeAs('images/categories', $fileName);

            $category->image()->create(['path'  => $fileName]);
        }

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.container')

@section('heading')
Create a new category
@endsection

@section('panel')
<form method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data">
		{{ csrf_field() }}

		<div class="form-group">
    		<label for="name">Name</label>
    		<input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Enter the name value">
		</div>
		<div class="form-group">
			<label for="status">Status</label>
			<select name="status" class="form-control" id="status" value="{{ old('status') }}">
			@foreach($status->dropdown() as $id => $name)
				<option value="{{ $id }}">{{ $name }}</option>
			@endforeach
			</select>
		</div>
		<div class="form-group">
		    <label for="image">Image <small>(only jpg/gif/png extensions are supported)</small></label>
		    <input type="file" class="form-control" id="image" name="image" value="{{ old('image') }}" placeholder="Enter the image value">
		</div>
		<div class="form-group">
		    <input type="submit" class="btn btn-info btn-block btn-sm" value="Create">
		</div>
</form>		
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.container')

@section('heading')
Edit category "{{ $category->name }}"
@endsection

@section('panel')
<form method="post" action="{{ route('categories.update', $category->id) }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<input type="hidden" name="_method" value="PUT">

		<div class="form-group">
    		<label for="name">Name</label>
    		<input type="text" class="form-control" id="name" name="name" value="{{ $category->name }}" placeholder="Enter the name value">
		</div>
		<div class="form-group">
			<label for="status">Status</label>
			<select name="status" class="form-control" id="status">
			@foreach($status->dropdown() as $id => $name)
				<option value="{{ $id }}" {{ $category->status === $id ? 'selected' : '' }} >{{ $name }}</option>
			@endforeach
			</select>
		</div>
		<div class="form-group">
		    <label for="image">Image <small>(only jpg/gif/png extensions are supported)</small></label>
		    <input type="file" id="image" name="image">

		    @if($category->image)
		    	<div style="margin:5px">
		    		<img class="img-rounded" src="{{ $category->image->getFullPath() }}" width="120" height="100">
		    	</div>
		    @endif
		</div>
		<div class="form-group">
		    <input type="submit" class="btn btn-info btn-block btn-sm" value="Save">
		</div>
</form>		
@endsection

resources/views/categories/index.blade.php
@extends('layouts.container')

@section('heading')
Categories
@endsection

@section('panel')

<div class="row" style="margin-bottom: 10px">
	<div class="col-md-6">
		<a href="{{ route('categories.create') }}" class="btn btn-info btn-block btn-sm">Create a new category</a>
	</div>
</div>
<div>
@if($categories->isEmpty())
	<div class="alert alert-warning">
		No available categories was found.
	</div>
@else
<div class="row">
	<div class="col-md-12">
	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Image</th>
				<th>Status</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach($categories as $category)
			<tr>
				<td>{{ $category->id }}</td>
				<td>{{ $category->name }}</td>
				<td>
					@if($category->image)
						<img src="{{ $category->image->getFullPath() }}" width="120" height="100">
					@else
						None
					@endif
				</td>
				<td>
					{{ $status->getStatusName($category->status) }}
				</td>
				<td>
						<form action="{{ route('categories.destroy', $category->id) }}" method="post">
							{{ csrf_field() }}
							<input type="hidden" name="_method" value="DELETE">
							
							<div class="btn-group">
								<a href="{{ route('categories.edit', $category->id) }}" class="btn btn-warning btn-sm">Edit</a>
								<input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm" 
									onclick="if (! confirm('Destroy category?')) return false">
							</div>
						</form>
					
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-5">
		{{ $categories->links() }}
	</div>
</div>
@endif
@endsection