routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

/** @var Router $router */

use Illuminate\Routing\Router;

$router->get('/', function () {
    return view('welcome');
});

// Authentication Routes...
$router->get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('throttle:5,1');
$router->post('login', 'Auth\LoginController@login')->middleware('throttle:5,1');
$router->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//$router->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//$router->post('register', 'Auth\RegisterController@register');

//$router->get('/fresh-users', function() {
//    App\User::all()->each(function(\App\User $user) {
//        $user->delete();
//    });
//});

// Password Reset Routes...
$router->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$router->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$router->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$router->post('password/reset', 'Auth\ResetPasswordController@reset');



$router->group(['prefix' => 'admin', 'middleware' => 'auth'], function(Router $router) {

	$router->resources([
		'categories'	=> 'CategoriesController',
		'products'		=> 'ProductsController',
		'orders'		=> 'OrdersController',
	]);
});

$router->get('/home', 'HomeController@index');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @if(! Auth::guest())
                        <li><a href="{{ route('categories.index') }}">Categories</a></li>
                        <li><a href="{{ route('products.index') }}">Products</a></li>
                        <li><a href="{{ route('orders.index') }}">Orders</a></li>
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')

        {{-- <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">@section('title')Dashboard @show</div>

                        <div class="panel-body">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div> --}}
        
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>

    @section('resources')

    @show
</body>
</html>

resources/views/layouts/container.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
        @if(! $errors->isEmpty())
            <div class="alert alert-danger">
                <ul>
                @foreach($errors->all() as $message)
                    <li>{{ $message }}</li>
                @endforeach
                </ul>
            </div>
        @endif
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">@yield('heading', 'Dashboard')</div>

                <div class="panel-body">
                        @section('panel')
                            Welcome to admin panel
                        @show
                </div>
            </div>
        </div>
    </div>
</div>
@endsection